//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using MySql.Data.MySqlClient;
using System;
using Model;
using System.Collections.Generic;

namespace Model
{
	[Serializable]
	public class Service
	{
        public Int64 Company_id { get; set; }
		public String Title { get; set; } 
		public Decimal Price { get; set; } 
		public Int32 Period { get; set; }
		public Int32 PeriodsPaid { get; set; }
		public Decimal Effectiveness { get; set; }		
		
		public Int64 Enterprise_id { get; set; }
		
		public virtual Company Company { get; set; }

        public Service(Int64 company_id, String title, Decimal price, Int32 period, Int32 periodsPaid, 
		               Decimal effectiveness, Int64 enterprise_id)
		{
            Company_id = company_id;
			Title = title;
			Price = price;
			Period = period;
			PeriodsPaid = periodsPaid;
			Enterprise_id = enterprise_id;
			Effectiveness = effectiveness;		
		}
	}
}